paquetes_base:
  - git
  - curl
  - wget
  - unzip
  - net-tools
  - htop
  - tree

usuario_local: ubuntu
repo_url: https://github.com/Quontyx/IJ-Systems-Automation.git
proyecto_dir: /home/ubuntu/IJ-Systems-Automation
