server {
    listen 80;
    server_name _;

    # Pagina principal
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Prometheus — pasa el path completo sin modificar
    location /prometheus {
        proxy_pass          http://172.30.30.10:9090;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # cAdvisor — pasa el path completo sin modificar
    location /metricas {
        proxy_pass          http://172.30.30.40:8080;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
